name: "Build Binaries"
on:
  workflow_dispatch:
    # This Action only starts when you go to Actions and manually run the workflow.

jobs:
  package:
    strategy:
      matrix:
        include:
          - platform: macos-latest
            arch: arm64
          - platform: windows-latest
            arch: amd64

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build Binaries
        working-directory: ./GoLangSource
        run: go build -buildmode=c-shared -o ./compiled/${{ matrix.platform }}-${{ matrix.arch }}.so
        env:
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 1
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: ./compiled/${{ matrix.platform }}-${{ matrix.arch }}.so
